version: "3.1"
services:
  appserver:
    build:
       context: .
       dockerfile: Dockerfile
    image: spring_boot_docker
    ports:
      - "8080:8080"
    networks:
      - local-network
networks:
  local-network:
  payment:
    driver: overlay
